from django.forms import ModelForm, HiddenInput, Select, EmailInput, Textarea, TextInput, FileInput, NumberInput
from .models import *


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        widgets = {
            'sub_client': HiddenInput(),
            'invoice_for_month': Select(attrs={'class': 'form-control'}),
            'date': TextInput(attrs={'class': 'form-control'}),
            'work_order_number': HiddenInput(),
            # 'bill_raised': TextInput(attrs={'class': 'form-control'}),
            'payment': Select(attrs={'class': 'form-control'}),
            'payment_details': TextInput(attrs={'class': 'form-control'}),
            'csr_status': Select(attrs={'class': 'form-control'}),
            'remark': Textarea(attrs={'class': 'form-control'}),
            'client': HiddenInput(),
            'order_id': HiddenInput(),
            'uid': HiddenInput(),
            'company': HiddenInput(),
            'payment_date': HiddenInput(),
            'bank_transfer': HiddenInput(),
            'total': HiddenInput(),
            'service_1': Select(attrs={'class': 'form-control'}),
            'service_2': Select(attrs={'class': 'form-control'}),
            'service_3': Select(attrs={'class': 'form-control'}),
            'service_4': Select(attrs={'class': 'form-control'}),
            'rate_1': HiddenInput(),
            'rate_2': HiddenInput(),
            'rate_3': HiddenInput(),
            'rate_4': HiddenInput(),
            'area_1': NumberInput(attrs={'class': 'form-control'}),
            'area_2': NumberInput(attrs={'class': 'form-control'}),
            'area_3': NumberInput(attrs={'class': 'form-control'}),
            'area_4': NumberInput(attrs={'class': 'form-control'}),
            'price_1': NumberInput(attrs={'class': 'form-control'}),
            'price_2': NumberInput(attrs={'class': 'form-control'}),
            'price_3': NumberInput(attrs={'class': 'form-control'}),
            'price_4': NumberInput(attrs={'class': 'form-control'}),
            # 'service_1': HiddenInput(),
            # 'service_2': HiddenInput(),
            # 'service_3': HiddenInput(),
            # 'service_4': HiddenInput(),
            # 'price_1': HiddenInput(),
            # 'price_2': HiddenInput(),
            # 'price_3': HiddenInput(),
            # 'price_4': HiddenInput(),
            # 'area_1': HiddenInput(),
            # 'area_2': HiddenInput(),
            # 'area_3': HiddenInput(),
            # 'area_4': HiddenInput(),
            # 'rate_1': HiddenInput(),
            # 'rate_2': HiddenInput(),
            # 'rate_3': HiddenInput(),
            # 'rate_4': HiddenInput(),
            'work_order_period': HiddenInput(),
            'frequency': HiddenInput(),
            'challan_text': Textarea(attrs={'class': 'form-control'}),
            'CSR': HiddenInput(),
            'serial_no': HiddenInput(),
        }
