# Generated by Django 3.0.4 on 2021-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
