# Generated by Django 3.0.4 on 2022-04-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_company'),
        ('client', '0004_auto_20210213_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=200, null=True)),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_1', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_2', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_3', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_4', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('upload_document', models.FileField(blank=True, upload_to='document_uploaded/')),
                ('work_order_period', models.CharField(max_length=100, null=True)),
                ('frequency', models.CharField(max_length=100, null=True)),
                ('CSR', models.IntegerField(default=0)),
                ('challan_text', models.TextField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('service_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_1', to='service.Service')),
                ('service_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_2', to='service.Service')),
                ('service_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_3', to='service.Service')),
                ('service_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_4', to='service.Service')),
            ],
        ),
    ]
