# Generated by Django 3.0.4 on 2022-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_sub_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_client',
            name='area_1',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='area_2',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='area_3',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='area_4',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='rate_1',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='rate_2',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='rate_3',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='rate_4',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='service_1',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='service_2',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='service_3',
        ),
        migrations.RemoveField(
            model_name='sub_client',
            name='service_4',
        ),
    ]
