# Generated by Django 3.0.4 on 2022-08-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220809_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_client',
            name='challan_text',
        ),
    ]
