# Generated by Django 3.0.4 on 2021-04-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210115_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
