# Generated by Django 3.0.4 on 2021-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210403_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
