# Generated by Django 3.0.4 on 2021-02-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_address'),
        ('service', '0002_service_company'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=8, null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
        ),
    ]
