# Generated by Django 3.0.4 on 2021-02-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210213_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
