# Generated by Django 3.0.4 on 2021-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210213_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Bill_for_month',
            field=models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEP', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='JAN', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
