# Generated by Django 3.0.4 on 2021-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210415_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_services',
            field=models.IntegerField(default=1),
        ),
    ]
