# Generated by Django 3.0.4 on 2021-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210416_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid(Cash)', 'Paid(Cash)'), ('Paid(A/c)', 'Paid(A/c)')], default='Pending', max_length=100),
        ),
    ]
