# Generated by Django 3.0.4 on 2021-07-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210701_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Bill_for_month',
            new_name='bill_for_month',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment',
        ),
    ]
