# Generated by Django 3.0.4 on 2021-07-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210701_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bill_for_month',
            new_name='work_order_period',
        ),
    ]
