# Generated by Django 3.0.4 on 2021-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210701_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csr',
            field=models.IntegerField(default=0),
        ),
    ]
