# Generated by Django 3.0.4 on 2021-07-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210710_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='work_order_period_to',
            new_name='work_order_period_To',
        ),
    ]
