# Generated by Django 3.0.4 on 2021-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210710_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='csr',
            new_name='CSR',
        ),
        migrations.AddField(
            model_name='order',
            name='TDS',
            field=models.IntegerField(default=0),
        ),
    ]
