# Generated by Django 3.0.4 on 2021-07-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210710_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_order_period_From',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_period_To',
            field=models.CharField(max_length=100),
        ),
    ]
