# Generated by Django 3.0.4 on 2021-07-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210710_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='work_order_period_From',
            new_name='work_order_period',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_order_period_To',
        ),
    ]
