# Generated by Django 3.0.4 on 2021-07-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20210710_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frequency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_period',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
