# Generated by Django 3.0.4 on 2021-07-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20210710_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upload_document',
            field=models.FileField(blank=True, upload_to='document_uploaded/'),
        ),
    ]
