# Generated by Django 3.0.4 on 2021-07-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_upload_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='no_of_services',
        ),
    ]
