# Generated by Django 3.0.4 on 2021-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20210710_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csr_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
