# Generated by Django 3.0.4 on 2021-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20210811_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='csr_status',
            field=models.BooleanField(choices=[(True, 'Paid'), (False, 'Not Paid')], default=False),
        ),
    ]
