# Generated by Django 3.0.4 on 2021-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20210811_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='challan_text',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
