# Generated by Django 3.0.4 on 2021-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_challan_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_raised',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
