# Generated by Django 3.0.4 on 2021-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20210906_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
