# Generated by Django 3.0.4 on 2021-12-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_bank_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service',
            new_name='service_1',
        ),
    ]
