# Generated by Django 3.0.4 on 2021-12-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_company'),
        ('order', '0034_auto_20211201_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_2', to='service.Service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_1', to='service.Service'),
        ),
    ]
