# Generated by Django 3.0.4 on 2021-12-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_company'),
        ('order', '0035_auto_20211201_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_3', to='service.Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_4', to='service.Service'),
        ),
    ]
