# Generated by Django 3.0.4 on 2021-12-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20211228_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
