# Generated by Django 3.0.4 on 2021-12-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
