# Generated by Django 3.0.4 on 2022-03-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20211228_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rate',
            new_name='area_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
        migrations.AddField(
            model_name='order',
            name='area_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='area_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='area_4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price_4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
