# Generated by Django 3.0.4 on 2022-03-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20220306_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
