# Generated by Django 3.0.4 on 2022-04-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_sub_client'),
        ('order', '0042_order_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TDS',
        ),
        migrations.AlterField(
            model_name='order',
            name='service_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Sub_Client'),
        ),
    ]
