# Generated by Django 3.0.4 on 2022-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20220411_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='challan_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_order_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
