# Generated by Django 3.0.4 on 2022-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_auto_20220512_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='colour_code',
            field=models.CharField(choices=[('ff6666', 'RED'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('ffffff', 'None')], default='None', max_length=20),
        ),
    ]
