# Generated by Django 3.0.4 on 2022-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_order_colour_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='colour_code',
            field=models.CharField(choices=[('#ffffff', 'None'), ('#ff6666', 'RED'), ('#99ffcc', 'GREEN'), ('#ffff99', 'YELLOW')], default='None', max_length=20),
        ),
    ]
