# Generated by Django 3.0.4 on 2022-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20220514_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='colour_code',
            field=models.CharField(choices=[('#ffffff', 'None'), ('#ffc7c7', 'RED'), ('#99ffcc', 'GREEN'), ('#ffff99', 'YELLOW')], default='None', max_length=20),
        ),
    ]
