# Generated by Django 3.0.4 on 2022-06-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20220514_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill_raised',
        ),
    ]
