# Generated by Django 3.0.4 on 2022-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_remove_order_bill_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
