# Generated by Django 3.0.4 on 2022-08-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20220809_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default='09/08/22', max_length=20, null=True),
        ),
    ]
